from __future__ import annotations

import argparse
from importlib.resources import files
from pathlib import Path

DEFAULT_CONFIG = """# PlannerCritic provider registry
# Edit this file to configure LLM providers for the planner and critic roles.

[roles]
planner = "local"
critic = "local"

[providers.local]
transport = "openai-compatible"
base_url = "http://localhost:11434/v1"
model = "llama3.2"
"""

#: The packaged demo goal (D11 §7) so ``init`` → ``plan`` works immediately.
_PACKAGED_GOAL_NAME = "quickstart.json"


def _packaged_goal_text() -> str:
    """Read the packaged demo goal bundled inside the wheel."""
    resource = files("planner_critic.demo").joinpath("data", _PACKAGED_GOAL_NAME)
    return resource.read_text(encoding="utf-8")


# ── Golden-path scaffolding templates (F-85, #155) ─────────────────────────

TEMPLATE_NAMES = [
    "k8s-gitops-deploy",
    "secops-incident-response",
    "supply-chain-patching",
    "data-eng-migration",
    "custom",
]

#: Which domain pack a template maps to (None = generic/custom).
_TEMPLATE_DOMAIN = {
    "secops-incident-response": "secops",
    "supply-chain-patching": "supply_chain",
    "data-eng-migration": "data_eng",
}

_DOMAIN_CONFIG_YAML = """# PlannerCritic domain configuration
name: {name}
description: {description}
"""

_CATALOG_YAML = """# Precondition catalog
preconditions:
  traffic_drained: "Traffic has been drained from the target"
  snapshot_created: "A recent snapshot of the resource exists"
"""

_GATES_PY = '''"""Domain gates for the {name} plan.

Each gate subclasses BaseGate and returns Findings for violations.
"""

from planner_critic.gates.base import BaseGate
from planner_critic.schema.plan import PlanVersion
from planner_critic.types import Finding, Severity


class PlaceholderGate(BaseGate):
    """A placeholder gate; replace with domain-specific checks."""

    name = "{name}_placeholder"

    def run(self, plan: PlanVersion) -> list[Finding]:
        return []
'''

_TEST_GATES_PY = '''"""Hermetic gate tests — generated by `plancritic init --template`.

These use the pytest-planner-critic plugin (no LLM, $0 in CI):
    pytest_plugins = ("planner_critic.pytest_plugin",)
"""

from planner_critic.pytest_plugin import assert_gate_passes


def test_placeholder_gate_is_clean():
    from planner_critic.schema.plan import PlanVersion

    plan = PlanVersion(
        id="plan",
        goal_id="goal",
        version=1,
        tasks=[],
    )
    from .gates import PlaceholderGate

    assert_gate_passes(PlaceholderGate(), plan)
'''

_MOCKS_YAML = """# Mock responses for hermetic testing (no LLM)
mocks:
  planner:
    - id: draft-1
      tasks: []
"""


def _template_payload(name: str) -> dict[str, str]:
    """Return the file payloads a template scaffolds.

    Args:
        name: One of :data:`TEMPLATE_NAMES`.

    Returns:
        A mapping of relative file path → file content.
    """
    if name == "custom":
        desc = "Custom domain pack (interactive)"
    else:
        desc = f"Golden-path template for {name}"
    return {
        "domain_config.yaml": _DOMAIN_CONFIG_YAML.format(name=name, description=desc),
        "preconditions/catalog.yaml": _CATALOG_YAML,
        "gates/__init__.py": _GATES_PY.format(name=name),
        "mocks/mocks.yaml": _MOCKS_YAML,
        "tests/test_gates.py": _TEST_GATES_PY,
    }


def list_templates() -> list[str]:
    """Return the available scaffolding template names.

    Returns:
        The list of :data:`TEMPLATE_NAMES`.
    """
    return list(TEMPLATE_NAMES)


def run_init_template(
    directory: str,
    template: str,
    *,
    force: bool = False,
    inject: bool = False,
) -> int:
    """Scaffold a golden-path project into ``directory``.

    Args:
        directory: The target directory to write into.
        template: One of :data:`TEMPLATE_NAMES`.
        force: Overwrite existing files when True.
        inject: When True, merge template files into an existing project
            without overwriting the marker config (``--force`` still
            controls per-file overwrite).

    Returns:
        0 on success, 1 when the template is unknown or the project exists
        without ``force`` or ``inject``.
    """
    if template not in TEMPLATE_NAMES:
        print(f"unknown template: {template!r}; choose from: {list_templates()}")
        return 1

    target = Path(directory).resolve()
    plancritic_dir = target / ".planner-critic"
    marker = target / "plancritic.toml"

    if marker.exists() and not force and not inject:
        print(f"project already exists at {target}; use --force or --inject to proceed")
        return 1

    plancritic_dir.mkdir(parents=True, exist_ok=True)
    if not marker.exists():
        marker.write_text(DEFAULT_CONFIG)

    payload = _template_payload(template)
    for rel, content in payload.items():
        out = plancritic_dir / rel
        if out.exists() and not force:
            continue
        out.parent.mkdir(parents=True, exist_ok=True)
        out.write_text(content)

    print(f"Scaffolded template {template!r} into {plancritic_dir}")
    print(f"  Config: {marker}")
    print(f"  Gates:  {plancritic_dir / 'gates'}")
    print("Generated tests use the pytest-planner-critic plugin (#156).")
    return 0


def build_init_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        prog="plancritic init",
        description="Scaffold a new PlannerCritic project (F-85)",
        add_help=False,
    )
    parser.add_argument(
        "--dir",
        default=".",
        help="Target directory (default: current directory)",
    )
    parser.add_argument(
        "--force",
        action="store_true",
        help="Overwrite existing files",
    )
    parser.add_argument(
        "--template",
        default=None,
        help=("Scaffold a golden-path template: " + ", ".join(TEMPLATE_NAMES)),
    )
    parser.add_argument(
        "--list-templates",
        action="store_true",
        help="List available templates and exit",
    )
    parser.add_argument(
        "--inject",
        action="store_true",
        help=(
            "Merge template files into an existing project "
            "(use with --template; skips existing files without --force)"
        ),
    )
    return parser


def run_init(argv: list[str]) -> int:
    args = build_init_parser().parse_args(argv)

    if args.list_templates:
        for name in list_templates():
            print(name)
        return 0

    if args.template:
        return run_init_template(args.dir, args.template, force=args.force, inject=args.inject)

    target = Path(args.dir).resolve()

    plancritic_dir = target / ".plancritic"
    config_path = target / "plancritic.toml"
    db_path = plancritic_dir / "plans.db"
    goal_path = plancritic_dir / "goal.json"

    if config_path.exists() and not args.force:
        print(f"plancritic.toml already exists at {config_path}; use --force to overwrite")
        return 1

    plancritic_dir.mkdir(parents=True, exist_ok=True)
    config_path.write_text(DEFAULT_CONFIG)
    db_path.write_text("")
    goal_path.write_text(_packaged_goal_text())

    print(f"Initialized PlannerCritic project in {target}")
    print(f"  Config: {config_path}")
    print(f"  Store:  {db_path}")
    print(f"  Example goal: {goal_path}")
    print(f"Run: plancritic plan {goal_path}")
    return 0


__all__ = [
    "TEMPLATE_NAMES",
    "build_init_parser",
    "list_templates",
    "run_init",
    "run_init_template",
]
